version: '3.3'
volumes:
  foodgram_pg_data:
  foodgram_media:
  foodgram_static:

services:
  foodgram_db:
    image: postgres:13.10
    volumes:
      - foodgram_pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

  backend:
    image: frostan/foodgram_backend
    volumes:
      - foodgram_static:/static/
      - foodgram_media:/media/
    depends_on:
      - foodgram_db
    env_file:
      - .env

  frontend:
    image: frostan/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - foodgram_static:/frontend_static
    depends_on:
      - backend
    restart: always

  nginx:
    image: frostan/foodgram_gateway
    env_file: .env
    ports:
      - "8001:80"
    volumes:
      - foodgram_static:/static/
      - foodgram_media:/media/
    depends_on:
      - frontend
    restart: always
