version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  foodgram_db:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: frostan/foodgram_backend
    depends_on:
      - foodgram_db
    env_file: ../.env
    volumes:
      - static:/backend_static
      - media:/media
    restart: always

  frontend:
    image: frostan/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
        - backend
  
  gateway:
    image: frostan/foodgram_gateway
    env_file: ../.env
    ports:
      - 8001:80
    volumes:
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media:/media
    depends_on:
      - frontend
    restart: always