# Generated by Django 3.2.3 on 2024-08-25 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
